# PortfolioProject/settings.py
"""
Django settings for PortfolioProject project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
# ----------------------------------------------------------------------------------------------------

from pathlib import Path
import os # -----
from dotenv import load_dotenv # -----

# Load the .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG') == 'True'

if not DEBUG:
    # 1. Add your PythonAnywhere username here
    ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '').split(',')
    
    # 2. SSL/HTTPS Security (Crucial for PythonAnywhere)
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    
else:
    # During local development, we allow everything and disable SSL redirect
    ALLOWED_HOSTS = ['*'] 
    # SHUT THESE OFF FOR LOCAL TESTING:
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'portfolio_app',  # portfolio pages -----
    'accounts.apps.AccountsConfig',  # user accounts (login/signup)
    'axes'  # stop brute force -----
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware', # -----
    'django.middleware.common.CommonMiddleware',
    'axes.middleware.AxesMiddleware', # -----
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'PortfolioProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')], # Template directory -----
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'accounts.context_processors.social_links',
            ],
        },
    },
]

WSGI_APPLICATION = 'PortfolioProject.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = [
    # Axes must be first
    'axes.backends.AxesBackend',
    'accounts.backends.CustomModelBackend',  # Custom backend for future extensibility
    'django.contrib.auth.backends.ModelBackend',
]

# --- AXES CONFIGURATION ---
AXES_FAILURE_LIMIT = 7               # Number of attempts before lockout
AXES_COOLOFF_TIME = 1                # Hours until the user can try again
AXES_LOCKOUT_TEMPLATE = 'accounts/pages/lockout.html'  # Custom "Hacker" lockout page
AXES_RESET_ON_SUCCESS = True         # Reset failures after a valid login
AXES_IP_WHITELIST_PROXY_COUNT = 1

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/
LANGUAGE_CODE = 'en'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

LANGUAGES = [
    ('en', 'English'),
    ('ja', 'Japanese'),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = '/static/'

# Tell Django where to look for top-level static files (like your root /static/ folder)
STATICFILES_DIRS = [
    BASE_DIR / 'static',  # Use the Path object for clean joining
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATIC_ROOT = BASE_DIR / 'staticfiles'

# Custom User Model
AUTH_USER_MODEL = 'accounts.CustomUser'

# --- Authentication Redirect URLs ---
# Directs to the URL pattern named 'login'
LOGIN_URL = 'accounts:login'
# After successful login, redirects user to the URL pattern named 'dashboard'
LOGIN_REDIRECT_URL = 'accounts:mypage'

# Email Backend (Console for testing)
# Temporarily set to console to see emails in the terminal
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# SMTP Settings (Commented out for production/later use)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# SMTP Settings
EMAIL_HOST_USER = os.getenv('EMAIL_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_PASS')
DEFAULT_FROM_EMAIL = f'CORE_SYSTEM <{EMAIL_HOST_USER}>'

# Set password reset/activation link timeout (in seconds)
# 600 seconds = 10 minutes
PASSWORD_RESET_TIMEOUT = 600
